### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by tmpfs** [maidsafe/blsttc#52]
Thanks for the library, I would like some clarification on the license please.

The README states we can choose from Apache-2 and MIT however in the `Cargo.toml` file the `license` is listed as `GPL-3.0`.

Can you please clarify that I am able to choose between Apache-2 and MIT?

Happy to submit a PR and update the `Cargo.toml` if the README is correct.

Thanks 🙏

**Comment by dirvine** [comment]
Yes, thanks for spotting that. If you do a PR then it's cool.
